### ISSUE TITLE
Faucet & send reveal sender's balance

### ISSUE THREAD

**Issue by unyilon** [massmux/SatsMobiBot#20]
/faucet and /send reveal to users the sender's current balance.

The sender's balance is shown on the below button 

![imagen](https://github.com/user-attachments/assets/a7ed717a-5190-43ca-8f4b-4e2a692d5cbc)
![imagen](https://github.com/user-attachments/assets/4f0e7fdf-11c7-4705-835a-9e7f0277f36d)

**Comment by massmux** [comment]
this has been fixed in https://github.com/massmux/SatsMobiBot/pull/21

**Comment by massmux** [comment]
This issue is closed and can be re open in case of need

**Comment by unyilon** [comment]
![image](https://github.com/user-attachments/assets/b6ea9418-af9d-4258-90b5-c8906abcf712)

Apparently it is still happening.
